# Docs: https://litestream.io/reference/config/

dbs:
  - path: ${NC_TOOL_DIR}noco.db
    replicas:
      - type: s3
        endpoint: ${LITESTREAM_S3_ENDPOINT}
        region: ${LITESTREAM_S3_REGION}
        skip-verify: ${LITESTREAM_S3_SKIP_VERIFY}
        bucket: ${LITESTREAM_S3_BUCKET}
        path: ${LITESTREAM_S3_PATH}
        access-key-id: ${LITESTREAM_S3_ACCESS_KEY_ID}
        secret-access-key: ${LITESTREAM_S3_SECRET_ACCESS_KEY}
        retention: ${LITESTREAM_RETENTION}
        retention-check-interval: ${LITESTREAM_RETENTION_CHECK_INTERVAL}
        snapshot-interval: ${LITESTREAM_SNAPSHOT_INTERVAL}
        sync-interval: ${LITESTREAM_SYNC_INTERVAL}
        # age:
        #   identities:
        #     - ${LITESTREAM_AGE_SECRET_KEY}
        #   recipients:
        #     - ${LITESTREAM_AGE_PUBLIC_KEY}
