name: "bumper"

on:
  pull_request_target:
    branches:
      - "develop"
    paths:
      - "pnpm-lock.yaml"

jobs:
  bumper:
    runs-on: nix

    permissions:
      contents: "write"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Run Bumper
        run: nix run .#bumper
